name: Alta Store API Testing in CI pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify
  test:
    name: Test Alta Store API Testing CI Pipeline
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v2
      - name: Test API Alta Store
        run: mvn clean verify